on:
  release:
    types: [published]

name: Release Build and Push
permissions:
    contents: read
    id-token: write

env:
  IMAGE: system-agent-installer-k3s
  REPO: rancher

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: true
        matrix:
          include:
            - arch: amd64
              os: linux
            - arch: arm64
              os: linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix the not-a-git-repository issue
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set environment variables
        run: |
          echo "ARCH=${{ matrix.arch }}" >> "$GITHUB_ENV"
          echo "OS=${{ matrix.os }}"     >> "$GITHUB_ENV"
          echo "GIT_TAG=$(echo "${{ github.ref_name }}" | sed -e 's/+/-/g')" >> "$GITHUB_ENV"

      - name: Download installer
        run: scripts/download

      - name: Load secrets from Vault
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials primeribs |  PRIME_RIBS ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials registry |  PRIME_REGISTRY ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials username |  PRIME_REGISTRY_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials password |  PRIME_REGISTRY_PASSWORD ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials registry |  PRIME_STAGING_REGISTRY ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials username |  PRIME_STAGING_REGISTRY_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials password |  PRIME_STAGING_REGISTRY_PASSWORD ;

      - name: Publish Image - Docker
        uses: rancher/ecm-distro-tools/actions/publish-image@master
        env:
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.os }}
        with:
          image: ${{ env.IMAGE }}
          tag: ${{ env.GIT_TAG }}-${{ matrix.os }}-${{ matrix.arch }}
          make-target: push-image

          public-repo: ${{ env.REPO }}
          public-username: ${{ env.DOCKER_USERNAME }}
          public-password: ${{ env.DOCKER_PASSWORD }}
          push-to-prime: false

      - name: Publish Image - Staging
        uses: rancher/ecm-distro-tools/actions/publish-image@master
        if: ${{ contains(github.ref_name, '-rc') }}
        env:
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.os }}
          PRIME_RIBS: ${{ env.PRIME_RIBS }}
        with:
          image: ${{ env.IMAGE }}
          tag: ${{ env.GIT_TAG }}-${{ matrix.os }}-${{ matrix.arch }}
          make-target: push-image

          push-to-public: false

          prime-repo: ${{ env.REPO }}
          prime-registry: ${{ env.PRIME_STAGING_REGISTRY }}
          prime-username: ${{ env.PRIME_STAGING_REGISTRY_USERNAME }}
          prime-password: ${{ env.PRIME_STAGING_REGISTRY_PASSWORD }}

      - name: Publish Image - Prime
        uses: rancher/ecm-distro-tools/actions/publish-image@master
        if: ${{ !contains(github.ref_name, '-rc') }}
        env:
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.os }}
          PRIME_RIBS: ${{ env.PRIME_RIBS }}
        with:
          image: ${{ env.IMAGE }}
          tag: ${{ env.GIT_TAG }}-${{ matrix.os }}-${{ matrix.arch }}
          make-target: push-image

          push-to-public: false

          prime-repo: ${{ env.REPO }}
          prime-registry: ${{ env.PRIME_REGISTRY }}
          prime-username: ${{ env.PRIME_REGISTRY_USERNAME }}
          prime-password: ${{ env.PRIME_REGISTRY_PASSWORD }}

  create-docker-manifest:
    runs-on: ubuntu-latest
    needs: [ build-linux ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          . scripts/version

      - name: Set Release tag
        run: |
          echo "GIT_TAG=$(echo "${{ github.ref_name }}" | sed -e 's/+/-/g')" >> "$GITHUB_ENV"

      - name: Load secrets from Vault
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials primeribs |  PRIME_RIBS ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials registry |  PRIME_REGISTRY ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials username |  PRIME_REGISTRY_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials password |  PRIME_REGISTRY_PASSWORD ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials registry |  PRIME_STAGING_REGISTRY ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials username |  PRIME_STAGING_REGISTRY_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials password |  PRIME_STAGING_REGISTRY_PASSWORD ;

      - name: Publish Manifest - Docker
        uses: rancher/ecm-distro-tools/actions/publish-image@master
        with:
          image: ${{ env.IMAGE }}
          tag: ${{ env.GIT_TAG }}
          make-target: publish-manifest

          public-repo: ${{ env.REPO }}
          public-username: ${{ env.DOCKER_USERNAME }}
          public-password: ${{ env.DOCKER_PASSWORD }}
          push-to-prime: false

      - name: Inspect Docker image
        run: docker buildx imagetools inspect ${{ env.REPO }}/${{ env.IMAGE }}:${{ env.GIT_TAG }}

      - name: Publish Manifest - Staging
        uses: rancher/ecm-distro-tools/actions/publish-image@master
        if: ${{ contains(github.ref_name, '-rc') }}
        with:
          image: ${{ env.IMAGE }}
          tag: ${{ env.GIT_TAG }}
          make-target: publish-manifest

          push-to-public: false

          prime-repo: ${{ env.REPO }}
          prime-registry: ${{ env.PRIME_STAGING_REGISTRY }}
          prime-username: ${{ env.PRIME_STAGING_REGISTRY_USERNAME }}
          prime-password: ${{ env.PRIME_STAGING_REGISTRY_PASSWORD }}

      - name: Inspect Staging image
        if: ${{ contains(github.ref_name, '-rc') }}
        run: docker buildx imagetools inspect ${{ env.PRIME_STAGING_REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ env.GIT_TAG }}

      - name: Publish Image - Prime
        uses: rancher/ecm-distro-tools/actions/publish-image@master
        if: ${{ !contains(github.ref_name, '-rc') }}
        with:
          image: "system-agent-installer-k3s"
          tag: ${{ env.GIT_TAG }}
          make-target: publish-manifest

          push-to-public: false

          prime-repo: ${{ env.REPO }}
          prime-registry: ${{ env.PRIME_REGISTRY }}
          prime-username: ${{ env.PRIME_REGISTRY_USERNAME }}
          prime-password: ${{ env.PRIME_REGISTRY_PASSWORD }}

      - name: Inspect Prime image
        if: ${{ !contains(github.ref_name, '-rc') }}
        run: docker buildx imagetools inspect ${{ env.PRIME_REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ env.GIT_TAG }}
